### PR TITLE
#75 Removes "puzzle" label on closing issue.

### PR DESCRIPTION
**Pull request by criske**
PR for #75.

Also made PuzzleComponent testable.

### CODE REVIEW

**Comment by zoeself** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by criske** [comment]
@amihaiemil it may be a little large pr, but from on, it will be easier to test PuzzleComponent.

**Comment by zoeself** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by amihaiemil** [comment]
@rultor merge it please

**Pull request merged**
